### PR TITLE
Refresh Vaadin 7 branch from master

### PR DESCRIPTION
**Pull request by ripla**

### CODE REVIEW

**Comment by johndevs** [comment]
Wouldn't this change break everyone elses builds if merged as the build system is changing?

**Comment by ripla** [comment]
@johndevs Do you mean users using the 1.3.x line? I tried to be careful with the package & artifact names so they would be the same as in the Gradle build. If you can find any issues, please let me know. :) Otherwise, I don't think developers should be much affected if the build system changes. Re-import to IDE should be all that's needed.

**Comment by johndevs** [comment]
@ripla It has more to do with needing to re-configure your CI builds than with IDE compatibility.

What is it you are trying to fix with this PR, it seems to have a little bit of everything in it? :)

**Comment by ripla** [comment]
@johndevs the Travis validation build seems to work. Is there something else that needs to be reconfigured? 

The goal of this PR is to add missing commits from master vs. 1.3.2. After this PR, I would release a new 1.3.3 version.

This is part of a bigger push to get rid of our private fork of DD layouts. The master is being updated for 8 beta 2 right now, and we thought to update the FW 7 line at the same time.

**Comment by johndevs** [comment]
Yea, I figured this. 

However, this addon is used by many more projects than just D. and breaking everyones custom build of the addon without a good reason is not really a good way of maintaining an open-source project. I'm sure D. can just as well use the artifact from the Directory even though it is built with whatever technology, so I'm sure you can get rid of the fork even though the whole build is not changed? 

Another good habit is making one PR per change, this PR has too many changes. For instance it downgrades to Java 7(?), it changes the Travis build, etc.

**Comment by ripla** [comment]
I don't have much experience in open-source projects, I didn't even think of other peoples custom builds! :) However, I did not change the build system on a whim. The current 1.3.2 doesn't build at all, and there is no combination of Framework 7 + Java 7 + Vaadin Gradle plugin + Gradle that currently works. That's why I was forced to change the build system to something that is able to build the project on Java 7.

Those commits could absolutely be in separate PR's. There is at least 1) cherry-picked commits from master 2) migrating the build file to Java 7 2) Migrating the project to Maven. Any thoughts on how you'd like those to be split/squashed?

**Comment by jreznot** [comment]
I also vote for Maven build, it seems with Vaadin Gradle plugin we have too much problems building this addon. We are planning to integrate our existing features to 1.3 branch and I look forward to the development process for this addon.

**Comment by ripla** [comment]
@johndevs any thoughts on how to move this forward? I can create separate PR's if needed.

**Comment by johndevs** [comment]
@ripla @jreznot  

Maybe we should first think about how we should handle the case that we will need to have two versions of the addon, one for Vaadin 7/Java 7 and one for Vaadin 8/Java 8. Until now it there hasn't been a need for this as it has only been for Vaadin 7, but the branches will start to diverge once the addon starts using the Vaadin 8 API's and the addon branches need to be maintained somehow.

Regarding Maven, I'm all for it if you want to use that instead. I was just curious about the problems you are facing with the Gradle build as I haven't noticed any major ones before. 

@ripla So I think the way to move forward would be to 
1) Decide branching strategy (and document that as contribution guidelines in the README)
2) Implement maven build for both branches if needed
3) Start integrating the pending PR's into the correct branches.

**Comment by ripla** [comment]
@johndevs created initial PR for updating branching strategy in #77. Please comment there. If it is good I'll merge it and update the Vaadin 7 branch as well. 

Master doesn't need to be converted to a Maven build, since it's running the latest versions and works well. But, if you feel that for consistency we need to have both branches running with the same build, let me know and I can create a PR for master as well.

**Comment by ripla** [comment]
I created #77 and #79 for updating the readme with branching information. This PR contains all that's needed to make the vaadin7 branch build correctly, so hopefully we can merge this soon.

**Comment by mstahv** [comment]
Hey, let's get forward! I think it would be best if @johndevs puts all available effort to develop Gradle support forward with the latest and greatest version. Let's merge these changes for v7 branch and go forward. I'd bet most of the development will happen in master and it should be pretty easy to backport changes if needed, even with different build scripts.

I'd keep the master on Gradle build still, even though Maven would probably be bit more familiar for most people. If there are still more contributors who'd favour Maven, we should probably reconsider, but until that, let's not fix it if it ain't broken.

**Pull request merged**
